name: Few-Shot Text Classification
description: Text classification application in several limited-labeled-data regimes using latent text embeddings
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-04-01"

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_dependencies
    script: cml/install_dependencies.py
    arguments: None
    short_summary: Create job to install dependencies.
    cpu: 2
    memory: 8
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_dependencies
    short_summary: Running install dependencies job. 

  - type: start_application
    short_summary: Starting few-shot text classification application 
    name: Few-Shot Text Classifier
    subdomain: fewshot
    script: apps/launch-fewshot-demo.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
    cpu: 2
    memory: 8
